### ISSUE TITLE
New installation of BigBrother breaks Dashboard.

### ISSUE THREAD

**Issue by qodo** [modmore/BigBrother#36]
I have just added BigBrother to a new MODX install and then added the Widget to the Dashboard and this returns a 500 error.
This seems to be working without issue with installations that already have it set up but not new ones.

I just get a blank screen with server 500 returned.

MODX log contains:

```
[2020-07-17 12:15:25] (ERROR @ /xyz/public_html/core/components/bigbrother/model/bigbrother/bigbrother.class.php : 366) Error refreshing oAuth2 token: The 'refresh_token' parameter must be defined for the refresh token grant type
[2020-07-17 12:15:25] (ERROR @ /xyz/public_html/core/components/bigbrother/model/bigbrother/bigbrother.class.php : 376) Could not refresh access token!
```

PHP Error log contains

```
[Fri Jul 17 12:15:25.417051 2020] [fcgid:warn] [pid 23436] [client IPADDRESS:52232] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /xyz/public_html/core/components/bigbrother/controllers/widget.class.php:51, referer: https://new.qodo.dev/manager/?a=workspaces
[Fri Jul 17 12:15:25.417093 2020] [fcgid:warn] [pid 23436] [client IPADDRESS:52232] mod_fcgid: stderr: Stack trace:, referer: https://new.qodo.dev/manager/?a=workspaces
[Fri Jul 17 12:15:25.417098 2020] [fcgid:warn] [pid 23436] [client IPADDRESS:52232] mod_fcgid: stderr: #0 /xyz/public_html/core/model/modx/moddashboardwidget.class.php(251): modDashboardWidgetBigBrother->render(), referer: https://new.qodo.dev/manager/?a=workspaces
[Fri Jul 17 12:15:25.417101 2020] [fcgid:warn] [pid 23436] [client IPADDRESS:52232] mod_fcgid: stderr: #1 /xyz/public_html/core/model/modx/moddashboardwidget.class.php(123): modDashboardWidgetInterface->process(), referer: https://new.qodo.dev/manager/?a=workspaces
[Fri Jul 17 12:15:25.417116 2020] [fcgid:warn] [pid 23436] [client IPADDRESS:52232] mod_fcgid: stderr: #2 /xyz/public_html/core/model/modx/moddashboard.class.php(83): modDashboardWidget->getContent(Object(WelcomeManagerController)), referer: https://new.qodo.dev/manager/?a=workspaces
[Fri Jul 17 12:15:25.417120 2020] [fcgid:warn] [pid 23436] [client IPADDRESS:52232] mod_fcgid: stderr: #3 /xyz/public_html/manager/controllers/default/welcome.class.php(73): modDashboard->render(Object(WelcomeManagerController)), referer: https://new.qodo.dev/manager/?a=workspaces
[Fri Jul 17 12:15:25.417123 2020] [fcgid:warn] [pid 23436] [client IPADDRESS:52232] mod_fcgid: stderr: #4 /xyz/public_html/core/model/modx/modmanagercontroller.class.php(155): WelcomeManagerController->process(Array), referer: https://new.qodo.dev/manager/?a=workspaces
[Fri Jul 17 12:15:25.417126 2020] [fcgid:warn] [pid 23436] [client IPADDRESS:52232] mod_fcgid: stderr: #5 /xyz/public_html/core/model/modx/modmanagerresponse.class.php(79): modMana in /xyz/public_html/core/components/bigbrother/controllers/widget.class.php on line 51, referer: https://new.qodo.dev/manager/?a=workspaces
```

This is 
MODX 2.7.3
PHP 7.2.24
Apache environment

Thanks!

**Comment by Mark-H** [comment]
This is already fixed in v1.4.1 which I'll release shortly.

**Comment by Mark-H** [comment]
1.4.1 is now available from the package manager.

**Comment by qodo** [comment]
Wow, thank you so much! :)
